# Generated by Django 3.2.5 on 2023-07-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230730_0755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioModel',
            new_name='Portfolio',
        ),
    ]
